### ISSUE TITLE
"due to access control checks" iOS

### ISSUE THREAD

**Issue by Naerian** [qrclip/capacitor-file-chunk#6]
Hi!

Some time I got "_**...due to access control checks**_" during "fetch" of "**appendChunkToFile**" method. I got this problem just in iOS. Android work fine.

I had the configuration for iOS in my Info.plist, but I dont know what is wrong.

**Comment by qrclip** [comment]
Does this error always happen or only sometimes? I hope it's the first one.

**Comment by Naerian** [comment]
Only sometimes...

I have implemented a logic to pause downloads. These are paused, and after complete fetch with "appendChunkToFile" it checks that state to exit the while loop that is responsible for controlling the "chunks".

With this I save the last chunk to know where to continue once the download resumes.

Like I said, this is working fine in Android, but iOS stop sometimes if i want to continue...

I used the "download01" example to this, and I set "tCurrentChunk" variable with the last "tCurrentChunk" after fetch to be able to resume download.

**Comment by qrclip** [comment]
Ok, the nasty random bugs ...  so what exactly do you do when you pause? Does the app go to pause when it goes to the background ? If so, you might want to include a pause button to test if the pause feature works (without the background state). On iOS, when the app goes into the background, the server shuts down immediately. There is an option to keep the server running, but when I tried it, it made no difference.

**Comment by Naerian** [comment]
Yeah... that rando bugs hahaha.

This error ocurrs with app active, without yet going into the background. When I pause the download (I have two buttons for this, pause and resume), app keep active. I have this code:

`...
do {

          const { done, value } = await tReader.read();
          if (done)
            break;

          const tempChunk = new Uint8Array(currentChunk.length + value.length);
          tempChunk.set(currentChunk);
          tempChunk.set(value, currentChunk.length);
          currentChunk = tempChunk;

          if (currentChunk.length >= chunkSize)
            break;

        } while (item.download_status === StatusDownloadType.downloading && !item.is_paused)

        tReader.releaseLock();

        const tCurrenchunkSize = currentChunk.length;
        if (tCurrenchunkSize > 0 && !item.is_paused) {

          const tOK = await item.fileChunkManager.appendChunkToFile(emptyFile, currentChunk);
          if (!tOK) {
            this._utilsService.avLog(`[downloadAndSaveBookInChunks] Download stopped.`, 'error');
            error = 'Error to append chunk to file!';
            break;
          }

          // Save last chunk
          item.current_chunk = tCurrentChunk;
          this._sqliteService.saveCurrentChunk(item, this.authUser.id);
          this._utilsService.avLog(`[downloadAndSaveBookInChunks] Save last chunk '${tCurrentChunk}'`);


          item.download_progress = Math.ceil(((tCurrentPos + tCurrenchunkSize) / fileSize) * 100);

          await new Promise<void>((resolve) => setTimeout(() => resolve(), 200));

          // IF ITEM IS PAUSED AFTER FINIS "FETCH", BREAK WHILE <-------------- ######
          if (item.is_paused) {
            break;
          }

          // Reset the currentChunk for the next range
          currentChunk = new Uint8Array();
        }
		...`

Like u can see, in the lane " if (item.is_paused) {", like we are using a while loop, its possile download was paused before "fetch" avobe has finished, so I breack that loop if after finish "fetch" item was paused.

After that, I can resume download calling same method to download normal item, but in this case setting "tCurrentChunk" with last "tCurrentChunk" got before pause.

Sorry if I don't explain myself correctly.

**Comment by qrclip** [comment]
At first glance, I don't see anything wrong with it, but it's only a small piece. I would try debugging the iOS server and logging all requests received. Maybe then it will become clear what is going on. Since the problem only occurs on iOS, it must be there, but since it's random, it may be less likely on Android, but the problem is still there. Again, it's hard to figure anything out without access to the iOS server logs.

**Comment by qrclip** [comment]
Any news about this issue ?

**Comment by angel-neoris** [comment]
No, nothing... its a random error...

U can close this issue for now, if u want.

**Comment by qrclip** [comment]
Ok, I'll close, if you can isolate the problem in a minimal app that you can send me, I'll be happy to debug and see if I can find the problem.
